---
title: JDSecDef Github Page
---
lsi: false
safe: true
source: JDSecDef.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
<<<<<<< HEAD
theme: jekyll-theme-minimal
=======
>>>>>>> fdde9fabbcb7f91722f9d4eee4e255d87e8f5982
